### ISSUE TITLE
setupPurchases got 5 arguments, expected 6

### ISSUE THREAD

**Issue by marcoancona** [RevenueCat/react-native-purchases#159]
**Describe the bug**
The app crashes on Android with the latest SDK. See screenshot below:

<img src="https://user-images.githubusercontent.com/2278117/88457529-bae99b00-ce87-11ea-8ab8-6992b76d8c45.png" width="300" />

1. Environment
    1. Platform: Android 11 (both simulator and real device)
    2. SDK version: 3.3.1
    3. OS version: Windows 10
    4. XCode/Android Studio version: Android Studio 4.0.1
    5. How widespread is the issue. Percentage of devices affected: N/A
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
```
2020-07-25 14:57:39.739 11149-11241/fit.foo.foofit E/unknown:ReactNative: Exception in native call
    com.facebook.react.bridge.NativeArgumentsParseException: RNPurchases.setupPurchases got 5 arguments, expected 6
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:348)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by vegaro** [comment]
Hi @marcoancona 

I have just been able to setup successfully on Android in the latest version. It's strange because `RNPurchases.setupPurchases` never accepted 6 arguments. Do you mind pasting here the contents of `RNPurchases.setupPurchases` in the `RNPurchasesModule.java` that is added to your Android Studio project? It would be helpful if you can also paste the `Purchases.setup` function from the index.js inside the `node_modules/react-native-purchases`.

Also, which version of React Native are you using?

Thanks!

**Comment by vegaro** [comment]
Closed due to inactivity

**Comment by AugustoAleGon** [comment]
@vegaro I got this error once I build the apk using `cd android && ./gradlew assembleRelease && cd ..`
![Screen Shot 2020-10-27 at 9 34 53 AM](https://user-images.githubusercontent.com/14319083/97317483-da061900-1838-11eb-8bc7-e62a483eb0e7.png)

This is what I see the android logcat.

I am using hermes as well. I don't know if that can help. Thanks.

**Comment by andrisole92** [comment]
Same issue

**Comment by aboedo** [comment]
@andrisole92 could you share the code you're using to set up, and the SDK version?

**Comment by masiamj** [comment]
@marcoancona @andrisole92 @aboedo Did you ever find a resolution here? I'm experiencing the a very similar issue, thanks!

**Comment by janechodance** [comment]
I'm experience similar issue on IOS as well. Any solution?
